### ISSUE TITLE
Refactorizar 

### ISSUE THREAD

**Issue by rotvulpix** [rotvulpix/dashcast#7]

**Comment by PythonProdigy** [comment]
Do we have an ETA on this ? What exactly are you planning to refactor? I need to make sure I can still run this on an old version of Node as I am using this in production for a commercial product. Also, any plans to switch to an MIT license?

**Comment by rotvulpix** [comment]
Personally, I think the code it's too messy and that's why I'm planning to refactor the entire project for ensuring maintainability. 

But, I'm interested of knowing about how you're using this project... In fact, that makes me glad :)

If you have more feedback I can do some fixes (because the main intention of this project is to create a prototype, not more than that). 

Feel free to send me an email with your feedback: rotvulpix@rotvulpix.cl

**Comment by PythonProdigy** [comment]
My lawyer suggested that I do not disclose any further information with you regarding this project. 

I appreciate all your work on this, keep it up.
